### ISSUE TITLE
[Planing] Improved UI / UX and standardise design

### ISSUE THREAD

**Issue by trickypr** [joelshepherd/tabliss#179]
One of the few things that are still in the planning stage for tabliss 2 is the UI / UX. I also figured that having a standardized design system may improve the speed of development and the quality of design.

# UI / UX changes
Feel free to comment below if you have any suggestions. 

- [ ] Make settings menu bigger (#115)
- [ ] Collapse local image list / all photo settings (#136)
- [ ] Add dark mode (#146)
- [ ] Put settings on separate floating cards (#154)

# Design standard
I am trying to gather as many design guidelines together. Bellow is an overview of all of them (so far). Feel free to suggest some bellow. 

| Name                 | Icons | React Library | 
| ---------------  | ----- | ------------- |
| Material Design | [✔️](https://material.io/resources/icons)| [✔️](https://material-ui.com/)|
| Ant Design | [✔️](https://ant.design/components/icon/)| [✔️ ](https://github.com/ant-design/ant-design)
| Polaris | [✔️](https://polaris-icons.shopify.com/)| [✔️](https://github.com/Shopify/polaris-react)

**Comment by AshokRaja10** [comment]
A lot of cues can be obtained from [Infinity tab pro extention](https://addons.mozilla.org/en-US/firefox/addon/infinity-new-tab-pro-firefox/)

- Grouping similar quick links into folders
- Having the favicon of the link as its icon
- Making the quick link section horizontally scrollable (https://github.com/joelshepherd/tabliss/issues/167)
-  To display auto-suggestions while typing on the Search box

**Comment by joelshepherd** [comment]
This is a great idea. Especially since I am not very good at design myself.

The main requirement for me on a UI framework though would be: lightweight. Time to first meaningful paint (boot speed) is pretty important for Tabliss; an extra 50ms is quite noticable.

Also Reactstrap could be added to the list too. It would be good to performance test some of these.

**Comment by trickypr** [comment]
# Performance 
(I am still testing performance but I need to make some notes so I won't forget them. I'll put performance data here once I am done testing)

## Notes

- Custom styles for material ui can be created with the makeStyles function
- Both Ant and Polaris require you to include a style sheet (Style sheet is on a CDN for Polaris) 
- Polaris requires you to put the contents of your app in an AppProvider tag

**Comment by wa4-fearless-otter** [comment]
Maybe add [bulma](https://bulma.io) to the design standard?

**Comment by trickypr** [comment]
I couldn't get that react library to work as well as I would have liked, but bulma's css is so simple that a react library is just extra overhead.

**Comment by CCreativeCND** [comment]
If your are still working on a dark theme, I used custom CSS to make make my own. Maybe this could be helpful to you?
```css
body {scrollbar-color: #2a2c2e #1c1e1f;}
.Settings .plane, .Settings div, .Settings .Widget {background-color: #121212}
.Settings h2, .Settings h3, .Settings h4, .Settings h5, .Settings span, .Settings label {color: #CCC}
p {color: #CCC}
.Settings textarea, .Settings select.primary, .Settings select, .Settings input, .Settings input[type=email], .Settings input[type=file], .Settings input[type=number], .Settings input[type=text], .Settings input[type=url], .Settings input[type=radio], .Settings input[type=checkbox] {background-color: #1D1D1D; color: #CCC; border: none}
.Settings .Widget .button--icon {color: white; background-color: #1D1D1D}
.Settings hr {border: 1px solid #1D1D1D}
::-webkit-scrollbar-track, ::-webkit-scrollbar-track-piece, ::-webkit-scrollbar-corner {background-color: #1D1D1D}
::-webkit-scrollbar-thumb {background-color: #2c2c2c}
::-webkit-scrollbar {background-color: #1D1D1D; color: #2c2c2c}
```
